### ISSUE TITLE
Output directory should be configurable

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/centos7-s2i-web-app#1]
Looking at React, Ember and Angular, their output directories are all slightly different.

React is build, Ember is dist and Angular is dist/APP_NAME

Probably default to "build"? and use a env var of `BUILD_DIR` to override

or `OUTPUT_DIR`?

**Comment by lholmquist** [comment]
@lance @danbev @helio-frota very important questions here ^^^

**Comment by lance** [comment]
I think that makes sense - prefer `BUILD_DIR` but don't really care much.

**Comment by danbev** [comment]
+1 on `OUTPUT_DIR`.

**Comment by helio-frota** [comment]
> "React is `build`, Ember is `dist` and Angular is `dist`/APP_NAME"

And about vuejs ?

(2 dist vs 1 build)

`DIST_DIR` can be used ?

if yes +1 to `DIST_DIR`

**Comment by lholmquist** [comment]
I think i ended up making it OUTPUT_DIR

**Comment by lholmquist** [comment]
should be in #7
