### ISSUE TITLE
Make the tests work

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/centos7-s2i-web-app#15]
Tests are currently not run since this was basically copied from the s2i-node image.  And a good chunk of those tests might not be relevant to this image.

We need to see what tests we can keep and what we get rid of and then re-enable travis

**Comment by helio-frota** [comment]
> We need to see what tests we can keep and what we get rid of and then re-enable travis

We have tests to check the connection with the test-example-app running.
I think this is enough since the other verification tests are done on the parent image.

**Comment by lholmquist** [comment]
There are a few parameters that we can send in, like DEPLOY_PORT, NPM_RUN and NPM_BUILD.  we might be able to test DEPLOY_PORT and maybe NPM_RUN,  but i'm not sure how to test the NPM_BUILD option
