### ISSUE TITLE
When extending from centos7-s2i-nodejs the env var NPM_RUN still with the same value on centos7-s2i-webapp. This is causing an error with make test.

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/centos7-s2i-web-app#18]
The test script will use the env var on this line :
https://github.com/bucharest-gold/centos7-s2i-web-app/blob/master/s2i/run#L11
And shows error command not found.

`NPM_RUN`: https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/Dockerfile#L13

We need to fix this to be able to move forward with the #15

**Comment by helio-frota** [comment]
Maybe override to empty string will fix `NPM_RUN= \` , I don't tested yet.

**Comment by lholmquist** [comment]
I think i originally used "NPM_RUN_COMMAND" which didn't have the issue,  but i think setting "NPM_RUN" to nothing like you suggested should take care of that

**Comment by helio-frota** [comment]
yea, but now I think "NPM_RUN_COMMAND" seems better than an empty var :smile:

**Comment by lholmquist** [comment]
landed in #19
