### ISSUE TITLE
Image streams are missing 12.x version

### ISSUE THREAD

**Issue by hiredgunhouse** [nodeshift/centos7-s2i-web-app#46]
Image streams are missing reference to 12.x version of the docker image.

**Comment by lholmquist** [comment]
I'm assuming you are talking about this file: https://github.com/nodeshift/centos7-s2i-web-app/blob/master/imagestreams/webapp-centos7.json ?

**Comment by lholmquist** [comment]
fixed in #49

**Comment by hiredgunhouse** [comment]
Yes, that's the file. Thank you.
