### ISSUE TITLE
Update Base image to use Nodejs UBI

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/centos7-s2i-web-app#51]
Since the nodeshift/centos7-s2i-nodejs images are being deprecated and no longer updated, we are going to move the ubi nodejs images

This issue should also include updates to the README, tests, etc....

We will be using ubi8

Node 10 : registry.access.redhat.com/ubi8/nodejs-10

Node 12: registry.access.redhat.com/ubi8/nodejs-12

**Comment by aalykiot** [comment]
Maybe this update will fix the issue I'm having (with eslint and node version) when I try to deploy react apps

**Log File**

﻿Receiving source from STDIN as archive ...
Receiving source from STDIN as archive ...
Using bucharestgold/centos7-s2i-web-app:10.x as the s2i builder image
tar: scripts: time stamp 2019-11-19 10:14:44 is 0.146798522 s in the future
tar: src/.gitignore: time stamp 2019-11-19 10:14:44 is 0.146000856 s in the future
tar: src/README.md: time stamp 2019-11-19 10:14:44 is 0.145931799 s in the future
tar: src/package.json: time stamp 2019-11-19 10:14:44 is 0.14587084 s in the future
tar: src/public/favicon.ico: time stamp 2019-11-19 10:14:44 is 0.145747309 s in the future
tar: src/public/index.html: time stamp 2019-11-19 10:14:44 is 0.145654623 s in the future
tar: src/public/logo192.png: time stamp 2019-11-19 10:14:44 is 0.145582384 s in the future
tar: src/public/logo512.png: time stamp 2019-11-19 10:14:44 is 0.145505123 s in the future
tar: src/public/manifest.json: time stamp 2019-11-19 10:14:44 is 0.14544532 s in the future
tar: src/public/robots.txt: time stamp 2019-11-19 10:14:44 is 0.145386216 s in the future
tar: src/public: time stamp 2019-11-19 10:14:44 is 0.145354993 s in the future
tar: src/src/App.css: time stamp 2019-11-19 10:14:44 is 0.145269101 s in the future
tar: src/src/App.js: time stamp 2019-11-19 10:14:44 is 0.145209638 s in the future
tar: src/src/App.test.js: time stamp 2019-11-19 10:14:44 is 0.144614653 s in the future
tar: src/src/index.css: time stamp 2019-11-19 10:14:44 is 0.144502974 s in the future
tar: src/src/index.js: time stamp 2019-11-19 10:14:44 is 0.144434644 s in the future
tar: src/src/logo.svg: time stamp 2019-11-19 10:14:44 is 0.144320096 s in the future
tar: src/src/serviceWorker.js: time stamp 2019-11-19 10:14:44 is 0.144251258 s in the future
tar: src/src: time stamp 2019-11-19 10:14:44 is 0.144219297 s in the future
tar: src/yarn.lock: time stamp 2019-11-19 10:14:44 is 0.142305269 s in the future
tar: src: time stamp 2019-11-19 10:14:44 is 0.142255778 s in the future
ls: cannot access /tmp/src/node_modules: No such file or directory
---> Installing application source
---> Building your Web Application from source
Current git config
url.https://github.com.insteadof=git@github.com: 
url.https://.insteadof=ssh:// 
url.https://github.com.insteadof=ssh://git@github.com 
---> Using 'yarn install' with YARN_ARGS
yarn install v1.10.1
[1/4] Resolving packages...
Using bucharestgold/centos7-s2i-web-app:10.x as the s2i builder image
tar: scripts: time stamp 2019-11-19 10:14:44 is 0.146798522 s in the future
tar: src/.gitignore: time stamp 2019-11-19 10:14:44 is 0.146000856 s in the future
tar: src/README.md: time stamp 2019-11-19 10:14:44 is 0.145931799 s in the future
tar: src/package.json: time stamp 2019-11-19 10:14:44 is 0.14587084 s in the future
tar: src/public/favicon.ico: time stamp 2019-11-19 10:14:44 is 0.145747309 s in the future
tar: src/public/index.html: time stamp 2019-11-19 10:14:44 is 0.145654623 s in the future
tar: src/public/logo192.png: time stamp 2019-11-19 10:14:44 is 0.145582384 s in the future
tar: src/public/logo512.png: time stamp 2019-11-19 10:14:44 is 0.145505123 s in the future
tar: src/public/manifest.json: time stamp 2019-11-19 10:14:44 is 0.14544532 s in the future
tar: src/public/robots.txt: time stamp 2019-11-19 10:14:44 is 0.145386216 s in the future
tar: src/public: time stamp 2019-11-19 10:14:44 is 0.145354993 s in the future
tar: src/src/App.css: time stamp 2019-11-19 10:14:44 is 0.145269101 s in the future
tar: src/src/App.js: time stamp 2019-11-19 10:14:44 is 0.145209638 s in the future
tar: src/src/App.test.js: time stamp 2019-11-19 10:14:44 is 0.144614653 s in the future
tar: src/src/index.css: time stamp 2019-11-19 10:14:44 is 0.144502974 s in the future
tar: src/src/index.js: time stamp 2019-11-19 10:14:44 is 0.144434644 s in the future
tar: src/src/logo.svg: time stamp 2019-11-19 10:14:44 is 0.144320096 s in the future
tar: src/src/serviceWorker.js: time stamp 2019-11-19 10:14:44 is 0.144251258 s in the future
tar: src/src: time stamp 2019-11-19 10:14:44 is 0.144219297 s in the future
tar: src/yarn.lock: time stamp 2019-11-19 10:14:44 is 0.142305269 s in the future
tar: src: time stamp 2019-11-19 10:14:44 is 0.142255778 s in the future
ls: cannot access /tmp/src/node_modules: No such file or directory
---> Installing application source
---> Building your Web Application from source
Current git config
url.https://github.com.insteadof=git@github.com: 
url.https://.insteadof=ssh:// 
url.https://github.com.insteadof=ssh://git@github.com 
---> Using 'yarn install' with YARN_ARGS
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[2/4] Fetching packages...
error @typescript-eslint/eslint-plugin@2.3.2: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "10.12.0"
error @typescript-eslint/eslint-plugin@2.3.2: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "10.12.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install  for documentation about this command.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install  for documentation about this command.
error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-web-app:10.x
error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-web-app:10.x

**Comment by lholmquist** [comment]
> Using bucharestgold/centos7-s2i-web-app:10.x as the s2i builder image

looks like i need to update that blog post :)   Looks like the image is the older one before we renamed the project from "bucharest-gold" to "nodeshift"

**Comment by aalykiot** [comment]
Oh I see, I'll try tomorrow to run the web apps example from the blog post again, with the correct image name and see if the deployment will be successful

**Comment by denkerny** [comment]
@aalykiot same issue with <code>react web app</code>, trying to use <code>latest</code> or <code>14.x</code>  <code>--imageTag</code>:

error jest-watch-typeahead@1.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.0".

how I know the reason is older <code>nodejs image</code> using, how often should the image `registry.access.redhat.com/ubi8/nodejs-${UBI_NODE_VERSION}` be updated?

**Comment by lholmquist** [comment]
These images getting updated on a less frequent cadence.  we can do a release to see if that fixes any issues.  We haven't release Node 16,  so once we do that, Node 16 should be the latest

**Comment by denkerny** [comment]
@lholmquist it would be great to use the latest minor version of each intended version ("^12.22.0 || ^14.17.0 || >=16.0.0")

**Comment by lholmquist** [comment]
i've updated the latest 14.x release and will do a 16 release soon.

**Comment by lholmquist** [comment]
there is now a 16.x and latest is now 16

**Comment by denkerny** [comment]
it helps (<code>fixed</code>), thx a lot
