### ISSUE TITLE
When `YARN_ENABLED=true`, `NPM_BUILD` override doesn't run

### ISSUE THREAD

**Issue by ponddesign** [nodeshift/centos7-s2i-web-app#63]
I noticed when we have `YARN_ENABLED=true`, we lose the ability to use the `NPM_BUILD` override variable:

https://github.com/nodeshift/ubi8-s2i-web-app/blob/1a457eccfff9cedbf6f68a1b624a211addd89af6/s2i/assemble#L60-L63

Would it be possible to have a `YARN_BUILD` (and `YARN_RUN`) override similar to the `NPM_` counterparts? Alternatively, perhaps the code could allow the override to run regardless of whether we're using NPM or Yarn.

**Comment by lholmquist** [comment]
Thanks for the PR,  the images on docker hub should be updated
