### ISSUE TITLE
Prune dev dependencies?

### ISSUE THREAD

**Issue by mhamann** [nodeshift/centos7-s2i-web-app#78]
It seems that this project is geared toward static sites or single-page apps (e.g. build the bundle, copy to output dir, serve it up).

What about apps where the server is also included? For example, I just used this to build a container that compiles an SPA into the "public" directory of an Express app, then copies the whole thing into the output directory, server and all.

In this case, it would be helpful to prune the dev dependencies to reduce the size of the container.

Any thoughts?

**Comment by lholmquist** [comment]
I think that is a valid use case,  but for that, i think you could use the plain Node.js image, `registry.access.redhat.com/ubi8/nodejs-14`, which does prune the dev deps

**Comment by mhamann** [comment]
I switched to your recommendation and there was much less friction for my specific use case. Thanks!
